# SITE CONFIGURATION
title: Vinicius Assef # your site title
author: viniciusban
description: > # Meta description of Homepage
  This blog have opinions exclusively from myself, a dev for 30+ years, and counting. I really love Python, shellscript and relational databases. I'm currently practicing one of the hardest skills in software development: name things correctly. Keep in touch.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://viniciusban.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: viniciusban
  links:
    - https://twitter.com/viniciusban
    - https://www.linkedin.com/in/viniciusban
    - https://github.com/viniciusban

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  i have much more questions than answers

hero_img: posts/iron-horse.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: viniciusban@gmail.com # email for form submission

twitter_username: viniciusban # replace with your_twitter_username or comment to remove link from footer
github_username:  viniciusban # replace with your_github_username or comment to remove link from footer
# instagram_username: shanlongjj # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: viniciusban # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
#permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
